name: dolphinecho
description: "A transcription app using local models."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  record: ^6.0.0
  path_provider: ^2.1.1
  flutter_secure_storage: ^9.2.4
  encrypt: ^5.0.3
  permission_handler: ^12.0.0+1
  file_picker: ^10.1.2
  provider: ^6.0.5
  uuid: ^4.1.0
  intl: ^0.20.2
  path: ^1.8.3
  vosk_flutter: ^0.3.48
  shared_preferences: ^2.2.3
  whisper_flutter_new: ^1.0.1
  flutter_svg: ^2.0.7
  skeletonizer: ^2.0.1
  ui_components:
    git:
      url: https://github.com/jan3dev/aqua-design-system.git
      ref: main
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/fonts/
    - assets/icons/
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/roboto_mono/RobotoMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto_mono/RobotoMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto_mono/RobotoMono-SemiBold.ttf
          weight: 600
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600

dependency_overrides:
  permission_handler: ^12.0.0+1
  skeletonizer: ^2.0.1
