name: echos
description: "A transcription app using local models."
publish_to: "none"
version: 0.0.1+6

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  archive: ^3.6.1
  cupertino_icons: ^1.0.8
  record: ^6.0.0
  path_provider: ^2.1.5
  flutter_secure_storage: ^9.2.4
  encrypt: ^5.0.3
  permission_handler: ^12.0.0+1
  provider: ^6.1.5
  uuid: ^4.5.1
  intl: ^0.20.2
  path: ^1.9.1
  vosk_flutter: ^0.3.48
  shared_preferences: ^2.5.3
  whisper_flutter_new: ^1.0.1
  flutter_svg: ^2.0.9
  skeletonizer: ^2.0.1
  ui_components:
    git:
      url: https://github.com/jan3dev/aqua-design-system.git
      ref: main
  url_launcher: ^6.3.1
  flutter_whisper_kit:
    git:
      url: https://github.com/jan3dev/flutter_whisper_kit.git
      path: packages/flutter_whisper_kit
      ref: main
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/models/whisper/ios/openai_whisper-tiny.zip
    - assets/models/whisper/android/ggml-tiny.bin.zip
    - assets/fonts/
    - assets/icons/
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/roboto_mono/RobotoMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto_mono/RobotoMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto_mono/RobotoMono-SemiBold.ttf
          weight: 600
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600

dependency_overrides:
  permission_handler: ^12.0.0+1
  skeletonizer: ^2.0.1
  flutter_whisper_kit_apple:
    git:
      url: https://github.com/jan3dev/flutter_whisper_kit.git
      path: packages/flutter_whisper_kit_apple
      ref: main
