name: echos
description: "A transcription app using local models."
publish_to: "none"
version: 0.0.1+7

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.9
  flutter_whisper_kit:
    git:
      url: https://github.com/jan3dev/flutter_whisper_kit.git
      path: packages/flutter_whisper_kit
      ref: main
  archive: ^3.6.1
  cupertino_icons: ^1.0.8
  record: ^6.0.0
  path_provider: ^2.1.5
  hooks_riverpod: ^2.6.1
  encrypt: ^5.0.3
  permission_handler: ^12.0.0+1
  provider: ^6.1.5
  uuid: ^4.5.1
  intl: ^0.20.2
  path: ^1.9.1
  vosk_flutter:
    git:
      url: https://github.com/jan3dev/vosk-flutter.git
      ref: 3f908da
  shared_preferences: ^2.5.3
  whisper_flutter_new: 
    git:
      url: https://github.com/jan3dev/whisper_flutter
      ref: d094ebd
  skeletonizer: ^2.0.1
  ui_components:
    path: packages/ui_components/
  url_launcher: ^6.3.1
  package_info_plus: ^8.3.0
  device_info_plus: ^12.2.0
  talker_flutter: ^4.9.3
  flutter_foreground_task: ^9.1.0
  share_plus: ^11.0.0
  synchronized: ^3.4.0
  haptic_feedback: ^0.5.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/models/
    - assets/models/whisper/ios/openai_whisper-tiny.zip
    - assets/models/whisper/android/ggml-tiny.bin.zip
    - assets/icons/
    - assets/images/

dependency_overrides:
  permission_handler: ^12.0.0+1
  skeletonizer: ^2.0.1
  flutter_whisper_kit_apple:
    git:
      url: https://github.com/jan3dev/flutter_whisper_kit.git
      path: packages/flutter_whisper_kit_apple
      ref: main

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "packages/ui_components/assets/app_icon.png"
  remove_alpha_channel_ios: true
