name: ui_components
description: "Design system for Echos app"
version: 0.0.1+1

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_svg: ^2.0.7
  intl: any
  flutter_localizations:
    sdk: flutter
  skeletonizer: ^2.0.1
  device_info_plus: ^12.2.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_gen_runner: 5.8.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/fonts/manrope/
    - assets/fonts/public_sans/
    - assets/svgs/
    - assets/svgs/flags/
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/manrope/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/manrope/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/manrope/Manrope-SemiBold.ttf
          weight: 600
    - family: PublicSans
      fonts:
        - asset: assets/fonts/public_sans/PublicSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/public_sans/PublicSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/public_sans/PublicSans-SemiBold.ttf
          weight: 600

flutter_gen:
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
  assets:
    enabled: true
    outputs:
      class_name: AquaUiAssets
      package_parameter_enabled: true
    inputs:
      - assets/animations/
  fonts:
    enabled: true
    outputs:
      class_name: AquaFontFamily
